// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.App = (function() {

    function App() {
      this.remove = __bind(this.remove, this);

      this.add = __bind(this.add, this);

      this.submit = __bind(this.submit, this);
      $('#form').on('submit', this.submit);
      $('#add').click(this.add);
      $('.delete').live('click', this.remove);
    }

    App.prototype.submit = function(event) {
      var data,
        _this = this;
      event.preventDefault();
      data = {};
      data.people = [];
      $('.person').each(function(index, element) {
        var age, email, name;
        name = $(element).find('.name').val();
        email = $(element).find('.email').val();
        age = $(element).find('.age').val();
        return data.people.push({
          name: name,
          email: email,
          age: age
        });
      });
      return console.log(data);
    };

    App.prototype.add = function() {
      return $('#people').append("<section class='person'>          <input type='text' class='name' placeholder='name'>          <input type='email' class='email' placeholder='email'>          <input type='text' class='age' placeholder='age'>          <button class='delete'>Delete</button>        </section>");
    };

    App.prototype.remove = function(event) {
      var parent;
      return parent = $(event.currentTarget).parents('.person').fadeOut(function() {
        return $(this).remove();
      });
    };

    return App;

  })();

  $(function() {
    return window.app = new App;
  });

}).call(this);
