// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQuery.fn.$_each = function(func) {
    return this.each(function() {
      return func.apply($(this));
    });
  };

  window.App = (function() {

    function App() {
      this.remove = __bind(this.remove, this);

      this.add = __bind(this.add, this);

      this.submit = __bind(this.submit, this);
      this.form = $('#form');
      this.add_button = $('#add');
      this.bindEvents();
      this.blank_form = this.people().first().clone();
      this.blank_form.css('display', 'none');
    }

    App.prototype.bindEvents = function() {
      this.form.on('submit', this.submit);
      this.add_button.click(this.add);
      return $('.delete').live('click', this.remove);
    };

    App.prototype.people = function() {
      return $('.person');
    };

    App.prototype.submit = function(event) {
      var data;
      event.preventDefault();
      data = [];
      this.people().$_each(function() {
        var to_add;
        to_add = {};
        this.find('input').$_each(function() {
          return to_add[this.attr('name')] = this.val();
        });
        return data.push(to_add);
      });
      return console.log(data);
    };

    App.prototype.add = function(event) {
      var person;
      event.preventDefault();
      person = this.blank_form.clone();
      $('#people').append(person);
      return person.fadeIn('slow');
    };

    App.prototype.remove = function(event) {
      var person,
        _this = this;
      event.preventDefault();
      person = $(event.target).parents('.person');
      return person.fadeOut(function() {
        person.remove();
        if ($('.person').length === 0) {
          return _this.add();
        }
      });
    };

    return App;

  })();

  $(function() {
    return window.app = new App;
  });

}).call(this);
