// Generated by CoffeeScript 1.4.0
(function() {
  var commands, describe, places, player, stdin, tryCommand;

  stdin = process.openStdin();

  stdin.setEncoding('utf8');

  player = {
    x: 0,
    y: 0,
    string: function() {
      return player.x + '' + player.y;
    }
  };

  places = {
    '00': 'The very centre of the universe',
    '01': 'The enchanted forest',
    '02': 'The crystal lake',
    '10': 'The mushroom kingdom',
    '11': 'The rotting garbage heap',
    '12': 'The infinite ocean',
    '20': 'The barren desert',
    '21': 'The icy wilderness',
    '22': 'The teeming forest'
  };

  describe = function() {
    var place;
    place = places[player.string()];
    if (place) {
      return console.log(place);
    } else {
      return console.log('nothing, nothing at all! better go back!');
    }
  };

  commands = {
    north: function() {
      console.log('you travel north');
      player.y -= 1;
      return describe();
    },
    south: function() {
      console.log('you travel south');
      player.y += 1;
      return describe();
    },
    east: function() {
      console.log('you travel east');
      player.x += 1;
      return describe();
    },
    west: function() {
      console.log('you travel west');
      player.x -= 1;
      return describe();
    },
    look: function() {
      console.log('you look around you, you can see:');
      return describe();
    },
    quit: function() {
      return process.exit();
    }
  };

  tryCommand = function(command) {
    var action;
    action = commands[command.trim()];
    if (action) {
      return action();
    } else {
      return console.log("Not sure how to " + (command.trim()));
    }
  };

  console.log('Welcome to the text adventure, your available commands are north, south, east, west, look and quit');

  stdin.on('data', tryCommand);

}).call(this);
